### PR TITLE
Error and stack trace

### LINKED ISSUE #517: BehaviorSubject/ValueStream - any way to access the last error if it occurred?
`BehaviorSubject` and `ValueStream` provided a way to check whether latest value exists and get its value if it does.

Wondering is it possible to have the equivalent for the latest error?

Actually I found it shouldn't be too difficult as `_Wrapper` has already recorded the latest error and stack trace. The only thing needed is just add a few API to expose it.

### PR DESCRIPTION
**Pull request by hoc081098**
### ISSUE
Fixes #517 
### BREAKING CHANGE:
- Change `ValueStream.error` to `ValueStream.errorAndStackTrace`:
   using  `stream.errorAndStackTrace?.error` instead of `stream.error`
- Change `ReplayStream.errors` to `ReplayStream.errorAndStackTraces`:
   using  `stream.errorAndStackTraces.map((es) => es.error).toList()` instead of `stream.errors`
- `Notification`: merge 2 fields `error` and `stackTrace` to `errorAndStackTrace`

### CODE REVIEW

File: lib/src/streams/connectable_stream.dart [hunk 1]
```diff
@@ -174,7 +175,7 @@ class ValueConnectableStream<T> extends ConnectableStream<T>
   bool get hasValue => _subject.hasValue;
 
   @override
-  Object get error => _subject.error;
+  ErrorAndStackTrace get errorAndStackTrace => _subject.errorAndStackTrace;
```
Comment (narcodico) [inline lib/src/streams/connectable_stream.dart:178]: `ErrorAndStackTrace` it's a weird naming. What do you feel about `RxError` or `ErrorDetails` ?

Comment (hoc081098) [reply lib/src/streams/connectable_stream.dart:178]: 😂 It's a weird name but IMO it's clear

Comment (narcodico) [reply lib/src/streams/connectable_stream.dart:178]: It doesn't get any clearer than that 😂

**Review by frankpepermans — APPROVED** [review]

**Comment by timnew** [comment]
The change looks great. May I ask is there any estimation that when it would go to formal version instead of beta?
